export const INITIAL_HOSPITAL_INFO = {
  name: "Vault Care Hospital",
  tagline: "Super Multi-Speciality Quaternary Medical Center",
  emergencyHotline: "+1 (800) 789-9999",
  generalDesk: "+1 (800) 789-1100",
  email: "care@vaultcarehospital.org",
  address: "742 Healthcare Blvd, Medical District, NY 10021",
  totalBeds: "650+",
  icuBeds: "140",
  operationTheaters: "14",
  doctorsCount: "120+",
  whatsapp: "18007899999",
  accreditations: ["NABH Gold Certified", "JCI International Standard", "ISO 9001:2015", "Green Hospital Award"],
};

export const INITIAL_DEPARTMENTS = [
  {
    id: "cardio",
    name: "Heart & Vascular Sciences",
    head: "Dr. Arvind V. Nambiar",
    image: "/departments/cardiology.jpg",
    bannerImage: "/departments/cardiology.jpg",
    beds: "85",
    description: "24/7 Primary Angioplasty, Hybrid Cath Labs, Minimally Invasive TAVR, and Heart Failure ICU.",
    badge: "24/7 Primary Cath Lab",
    specialties: ["Interventional Cardiology", "Cardiac Electrophysiology", "Minimally Invasive CABG", "Pediatric Heart Surgery"],
    services: ["Coronary Angioplasty & Stenting", "CABG Open Heart Surgery", "Pacemaker Implantation", "Heart Failure Clinic"],
    stats: "18,000+ Angioplasties",
  },
  {
    id: "neuro",
    name: "Neurosciences & Stroke Unit",
    head: "Dr. Rajeshwar Rao",
    image: "/departments/neurology.jpg",
    bannerImage: "/departments/neurology.jpg",
    beds: "60",
    description: "Comprehensive Stroke Center, Micro-Neurosurgery, 3T Silent MRI, and Neuro-Critical ICU.",
    badge: "Level-1 Stroke Response",
    specialties: ["Micro-Neurosurgery", "Stereotactic Radiosurgery", "Stroke Thrombectomy", "Spine Decompression"],
    services: ["Stroke Triage Unit", "Brain Tumor Surgery", "Spine Micro-Discectomy", "Epilepsy Management"],
    stats: "99.2% Thrombolysis Rate",
  },
  {
    id: "ortho",
    name: "Orthopedics & Robotic Joints",
    head: "Dr. Sarah Jenkins",
    image: "/departments/orthopedics.jpg",
    bannerImage: "/departments/orthopedics.jpg",
    beds: "70",
    description: "Mako Robotic Total Knee & Hip Replacements, Arthroscopic Sports Medicine, and Polytrauma Reconstruction.",
    badge: "Mako Robotic Navigation",
    specialties: ["Robotic Joint Replacement", "Sports Ligament Arthroscopy", "Complex Spine Surgery", "Pediatric Orthopedics"],
    services: ["Robotic Knee Replacement", "Total Hip Arthroplasty", "Sports Ligament Reconstruction", "Spine Decompression"],
    stats: "12,500+ Joint Surgeries",
  },
  {
    id: "onco",
    name: "Comprehensive Cancer Institute",
    head: "Dr. Margaret Thorne",
    image: "/departments/oncology.jpg",
    bannerImage: "/departments/oncology.jpg",
    beds: "90",
    description: "Precision Oncology, Robotic Surgical Oncology, HEPA Immunotherapy Wards, and Targeted Molecular Therapy.",
    badge: "Tumor Board Protocol",
    specialties: ["Medical Oncology", "Surgical Oncology", "Linear Accelerator Radiotherapy", "Bone Marrow Transplant"],
    services: ["Medical Oncology & Immunotherapy", "Surgical Tumor Resection", "Targeted Radiation Therapy", "Bone Marrow Transplant"],
    stats: "98.7% Precision Index",
  },
  {
    id: "pediatrics",
    name: "Pediatrics & Child Care",
    head: "Dr. Robert Sterling",
    image: "/departments/pediatrics.jpg",
    bannerImage: "/departments/pediatrics.jpg",
    beds: "50",
    description: "24/7 Level-III Neonatal ICU, Pediatric Intensive Care (PICU), and Advanced Child Specialty Clinics.",
    badge: "24/7 Level-III NICU",
    specialties: ["Neonatal Intensive Care", "Pediatric Surgery", "Child Development", "Pediatric Pulmonology"],
    services: ["Giraffe Infant Incubators", "Pediatric Emergency Triage", "Child Vaccination Hub", "Congenital Defect Surgery"],
    stats: "99.9% Neonatal Safety",
  },
  {
    id: "trauma",
    name: "24/7 Emergency & Level-1 Trauma",
    head: "Dr. David Sterling",
    image: "/departments/emergency.jpg",
    bannerImage: "/departments/emergency.jpg",
    beds: "45",
    description: "Dedicated Polytrauma Resuscitation Center, Direct Rooftop Helipad Elevators, and Mobile 5G ICU Fleet.",
    badge: "Direct Rooftop Helipad",
    specialties: ["Emergency Polytrauma", "Rapid Resuscitation", "Toxicology & Poisons", "Disaster Command Hub"],
    services: ["Rooftop Helipad Rapid Transfer", "Zero-Wait Trauma Resuscitation", "Immediate Whole-Body CT", "Automated Defibrillation"],
    stats: "< 4 Min Door-to-Doctor",
  },
  {
    id: "maternity",
    name: "Women, Maternity & Neonatology",
    head: "Dr. Elena Rostova",
    image: "/departments/maternity.jpg",
    bannerImage: "/departments/maternity.jpg",
    beds: "55",
    description: "LDRP Luxury Birthing Suites, High-Risk Maternal Medicine, 4D Fetal Scans, and Level-III Giraffe NICU.",
    badge: "Level-III Giraffe NICU",
    specialties: ["Luxury LDRP Suites", "High-Risk Pregnancy", "Fetal Medicine", "Advanced Neonatal Care"],
    services: ["LDRP Birthing Suites", "Painless Epidural Delivery", "High-Risk Maternal ICU", "4D Fetal Anomaly Scans"],
    stats: "25,000+ Safe Deliveries",
  },
  {
    id: "radiology",
    name: "3T Silent Radiology & Imaging",
    head: "Dr. Priya Sundaram",
    image: "/departments/radiology.jpg",
    bannerImage: "/departments/radiology.jpg",
    beds: "30",
    description: "Whisper-Quiet 3T Wide-Bore MRI, 256-Slice Dual Source Cardiac CT, and Automated Molecular Pathology.",
    badge: "6-Hour Cloud PACS",
    specialties: ["3T Silent Neuro MRI", "256-Slice CT Angio", "3D Tomosynthesis", "Nuclear PET-CT"],
    services: ["3T Wide-Bore Silent MRI", "256-Slice Dual Source CT", "Digital 3D Mammography", "Automated PACS Cloud Report"],
    stats: "99.8% Accuracy",
  },
];

export const INITIAL_DOCTORS = [
  {
    id: "doc-1",
    name: "Dr. Arvind V. Nambiar",
    role: "Chief Medical Officer & Senior Cardiologist",
    title: "Chief Medical Officer & Senior Cardiologist",
    department: "Heart & Vascular Sciences",
    departmentName: "Heart & Vascular Sciences",
    deptId: "cardio",
    experience: "32+ Years",
    experienceYears: "32",
    qualification: "MD, DM (Cardiology), FACC (USA), FSCAI",
    education: "MD, DM (Cardiology), FACC (USA), FSCAI",
    rating: 4.9,
    reviewsCount: 380,
    fee: "₹1,200",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=70",
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    timing: "09:00 AM - 02:00 PM",
    specialty: "Complex Angioplasty & TAVR",
    specialization: "Complex Angioplasty & TAVR",
    about: "Internationally renowned interventional cardiologist with over 18,000 coronary interventions and pioneer of minimally invasive transcatheter valves.",
  },
  {
    id: "doc-2",
    name: "Dr. Sarah Jenkins",
    role: "Director of Robotic Joint Replacement",
    title: "Director of Robotic Joint Replacement",
    department: "Orthopedics & Robotic Joints",
    departmentName: "Orthopedics & Robotic Joints",
    deptId: "ortho",
    experience: "24+ Years",
    experienceYears: "24",
    qualification: "MS (Ortho), M.Ch (UK), Fellow Robotic Surgery (USA)",
    education: "MS (Ortho), M.Ch (UK), Fellow Robotic Surgery (USA)",
    rating: 5.0,
    reviewsCount: 420,
    fee: "₹1,000",
    image: "https://images.unsplash.com/photo-1594824813576-92864c207d57?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1594824813576-92864c207d57?auto=format&fit=crop&w=400&q=70",
    availableDays: ["Mon", "Wed", "Fri", "Sat"],
    timing: "10:00 AM - 04:00 PM",
    specialty: "Mako Robotic Knee & Hip Arthroplasty",
    specialization: "Mako Robotic Knee & Hip Arthroplasty",
    about: "Pioneer in robotic arm-assisted sub-millimeter joint reconstruction with over 6,500 successful robotic joint procedures and rapid 24h patient ambulation.",
  },
  {
    id: "doc-3",
    name: "Dr. Rajeshwar Rao",
    role: "Senior Consultant Neurosurgeon & Spine Lead",
    title: "Senior Consultant Neurosurgeon & Spine Lead",
    department: "Neurosciences & Stroke Unit",
    departmentName: "Neurosciences & Stroke Unit",
    deptId: "neuro",
    experience: "28+ Years",
    experienceYears: "28",
    qualification: "M.Ch (Neurosurgery), FINR (Zurich), FACS",
    education: "M.Ch (Neurosurgery), FINR (Zurich), FACS",
    rating: 4.9,
    reviewsCount: 290,
    fee: "₹1,500",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=70",
    availableDays: ["Tue", "Thu", "Sat"],
    timing: "11:00 AM - 05:00 PM",
    specialty: "Brain Tumor Micro-Surgery & Endoscopic Spine",
    specialization: "Brain Tumor Micro-Surgery & Endoscopic Spine",
    about: "Expert in complex skull-base tumors, cerebrovascular bypass, and minimally invasive tubular endoscopic spinal decompression.",
  },
  {
    id: "doc-4",
    name: "Dr. Margaret Thorne",
    role: "Chief of Medical & Precision Oncology",
    title: "Chief of Medical & Precision Oncology",
    department: "Comprehensive Cancer Institute",
    departmentName: "Comprehensive Cancer Institute",
    deptId: "onco",
    experience: "26+ Years",
    experienceYears: "26",
    qualification: "MD, DM (Medical Oncology), ESMO Certified (Geneva)",
    education: "MD, DM (Medical Oncology), ESMO Certified (Geneva)",
    rating: 4.9,
    reviewsCount: 310,
    fee: "₹1,200",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=70",
    availableDays: ["Mon", "Tue", "Thu", "Fri"],
    timing: "09:30 AM - 03:30 PM",
    specialty: "Targeted Immunotherapy & Genomic Medicine",
    specialization: "Targeted Immunotherapy & Genomic Medicine",
    about: "Lead researcher in personalized cancer therapies, molecular pathology profiling, and state-of-the-art biological checkpoint inhibitors.",
  },
  {
    id: "doc-5",
    name: "Dr. David Sterling",
    role: "Head of Emergency Medicine & Trauma ICU",
    title: "Head of Emergency Medicine & Trauma ICU",
    department: "24/7 Emergency & Level-1 Trauma",
    departmentName: "24/7 Emergency & Level-1 Trauma",
    deptId: "trauma",
    experience: "20+ Years",
    experienceYears: "20",
    qualification: "MD (Emergency Medicine), FACEM (Australia)",
    education: "MD (Emergency Medicine), FACEM (Australia)",
    rating: 4.8,
    reviewsCount: 450,
    fee: "₹800",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=70",
    availableDays: ["24/7 Floor Active"],
    timing: "Round-the-Clock",
    specialty: "Polytrauma Resuscitation & Critical Care",
    specialization: "Polytrauma Resuscitation & Critical Care",
    about: "Directs Level-1 trauma response teams and aeromedical helicopter triage transfers with an average door-to-treatment time under 4 minutes.",
  },
  {
    id: "doc-6",
    name: "Dr. Elena Rostova",
    role: "Senior Consultant Obstetrician & Fetal Medicine",
    title: "Senior Consultant Obstetrician & Fetal Medicine",
    department: "Women, Maternity & Neonatology",
    departmentName: "Women, Maternity & Neonatology",
    deptId: "maternity",
    experience: "22+ Years",
    experienceYears: "22",
    qualification: "MD, DNB, MRCOG (London), Fellowship Fetal Medicine",
    education: "MD, DNB, MRCOG (London), Fellowship Fetal Medicine",
    rating: 5.0,
    reviewsCount: 340,
    fee: "₹1,000",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=70",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=70",
    availableDays: ["Mon", "Tue", "Wed", "Fri", "Sat"],
    timing: "10:00 AM - 03:00 PM",
    specialty: "High-Risk Pregnancy & Painless Delivery",
    specialization: "High-Risk Pregnancy & Painless Delivery",
    about: "Specializes in high-risk pregnancies, advanced 4D fetal ultrasound anomaly scans, and painless natural birthing protocols in luxury LDRP suites.",
  },
];

export const INITIAL_SERVICES = [
  {
    id: "srv-1",
    num: "01",
    title: "24/7 Emergency & Level-1 Trauma",
    category: "Emergency & Critical Care",
    badge: "Level-1 Trauma Certified",
    tagline: "< 4 Min Door-to-Doctor • Direct Helipad Link",
    headline: "Golden-Hour Polytrauma & Emergency Critical Care",
    description: "24/7 emergency surgical teams, mobile ICU ambulance dispatch, and instant trauma CT.",
    image: "/services/emergency.jpg",
    pricing: "Instant Triage • 100% Cashless TPA Insurance Covered",
    themeColor: "rose",
  },
  {
    id: "srv-2",
    num: "02",
    title: "Robotic & Minimally Invasive Surgery",
    category: "Robotic Surgical Sciences",
    badge: "Sub-Millimeter Navigation",
    tagline: "DaVinci XI & Mako Robotic Arm Suites",
    headline: "Robotic Joint Replacement & Precision Keyhole Surgery",
    description: "DaVinci XI & Mako robotic platforms with sub-millimeter surgical precision.",
    image: "/services/robotic.jpg",
    pricing: "Transparent Fixed Packages • Cashless Pre-Auth Assistance",
    themeColor: "indigo",
  },
  {
    id: "srv-3",
    num: "03",
    title: "Master Preventive Health & Screenings",
    category: "Preventive Care & Labs",
    badge: "6-Hour Digital PACS Report",
    tagline: "85+ Diagnostic Biomarkers • Full Organ Profiling",
    headline: "Executive Full-Body & Comprehensive Organ Profiling",
    description: "Personalized preventive diagnostic screenings with digital reports delivered in 6 hours.",
    image: "/services/preventive.jpg",
    pricing: "Packages from ₹4,999 • Tax-Exempt Healthcare",
    themeColor: "emerald",
  },
  {
    id: "srv-4",
    num: "04",
    title: "Tele-Consultation & Virtual Clinic",
    category: "Digital Healthcare",
    badge: "Instant Video OPD",
    tagline: "Encrypted HD Video Calls • Digital Prescriptions",
    headline: "Encrypted HD Video Consultation & Virtual Clinic",
    description: "Connect directly with top medical specialists from home with instant digital prescriptions.",
    image: "/services/teleconsult.jpg",
    pricing: "₹499 - ₹999 Fixed Consultation • No Hidden Fees",
    themeColor: "sky",
  },
  {
    id: "srv-5",
    num: "05",
    title: "Critical Care (ICU / NICU / CCU / PICU)",
    category: "Critical Care Units",
    badge: "1:1 Dedicated Nursing",
    tagline: "120 Advanced Isolation Beds • AI Tele-ICU",
    headline: "24/7 Intensivist-Led Multidisciplinary Critical Care",
    description: "120 Level-3 ICU isolation beds with advanced mechanical ventilation and ECMO support.",
    image: "/services/critical-care.jpg",
    pricing: "Direct Cashless TPA Billing • Transparent Daily Breakdown",
    themeColor: "amber",
  },
  {
    id: "srv-6",
    num: "06",
    title: "24/7 Automated Robotic Pharmacy",
    category: "Pharmacy Logistics",
    badge: "100% Genuine Barcoded Drugs",
    tagline: "Cold-Chain Maintained • Emergency Home Delivery",
    headline: "Zero-Error Robotic Dispensing & Doorstep Delivery",
    description: "10,000+ genuine life-saving medications with 2-8°C cold-chain maintenance.",
    image: "/services/pharmacy.jpg",
    pricing: "Transparent MRP Discounts • Insurance Reimbursable",
    themeColor: "teal",
  },
];

export const INITIAL_FACILITIES = [
  {
    id: "fac-1",
    title: "Level-3 Multidisciplinary ICU & ECMO Suites",
    category: "Critical Care",
    capacity: "120 Advanced Beds",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
    themeGradient: "from-amber-500 to-orange-600",
    image: "/services/critical-care.jpg",
    description: "120 isolation ICU cubicles with dedicated 1:1 nursing, HEPA filtration, and bedside dialysis/ECMO capabilities.",
    features: [
      "1:1 Critical Care Specialist & Dedicated Nurse Ratio",
      "Centralized Multi-Parameter AI Telemetry Hub",
      "Advanced Servo-U Mechanical Ventilators",
      "HEPA-Filtered Negative Pressure Airborne Isolation",
    ],
  },
  {
    id: "fac-2",
    title: "Modular DaVinci & Hybrid Robotic Operation Theatres",
    category: "Surgical Suites",
    capacity: "14 Ultra-Clean OTs",
    badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-200",
    themeGradient: "from-indigo-600 to-purple-600",
    image: "/services/robotic.jpg",
    description: "Ultra-clean laminar airflow Class-100 surgical suites equipped with DaVinci XI and Mako orthopedic robotic platforms.",
    features: [
      "DaVinci 4-Arm Multi-Quadrant Robotic Surgery Suite",
      "Mako CT-Guided Robotic Joint Arthroplasty Unit",
      "Full Glass Anti-Microbial Touchless OT Walls",
      "Integrated 4K 3D Laparoscopic Live Tele-Cast",
    ],
  },
  {
    id: "fac-3",
    title: "Advanced 3T Silent MRI & 256-Slice CT Diagnostic Wing",
    category: "Radiology & Imaging",
    capacity: "24/7 Digital PACS",
    badgeColor: "bg-sky-100 text-sky-800 border-sky-200",
    themeGradient: "from-sky-500 to-blue-600",
    image: "/departments/radiology.jpg",
    description: "State-of-the-art diagnostic imaging center offering low-dose high-speed CT scans, 3T quiet MRI, and instant cloud reporting.",
    features: [
      "Siemens 3T Silent Wide-Bore Neuro MRI",
      "GE Revolution 256-Slice Ultra-Low Dose Trauma CT",
      "Digital 3D Tomosynthesis Mammography Unit",
      "Instant 6-Hour PACS Cloud Diagnostic Reports",
    ],
  },
  {
    id: "fac-4",
    title: "24/7 Level-1 Emergency & Helipad Trauma Center",
    category: "Emergency & Trauma",
    capacity: "45 Resuscitation Bays",
    badgeColor: "bg-rose-100 text-rose-800 border-rose-200",
    themeGradient: "from-rose-500 to-red-600",
    image: "/services/emergency.jpg",
    description: "Dedicated polytrauma resuscitation center with direct rooftop helipad connectivity and immediate surgical access.",
    features: [
      "< 4 Minute Average Door-to-Emergency Physician",
      "Direct Rooftop Helipad Air Ambulance Elevators",
      "Dedicated On-Site Emergency Blood Transfusion Unit",
      "Mobile 5G Telemetry ICU Ambulance Fleet",
    ],
  },
  {
    id: "fac-5",
    title: "LDRP Luxury Maternity & Neonatal Intensive Care Wing",
    category: "Maternity & NICU",
    capacity: "65 Private Suites",
    badgeColor: "bg-pink-100 text-pink-800 border-pink-200",
    themeGradient: "from-pink-500 to-rose-600",
    image: "/departments/maternity.jpg",
    description: "Integrated Labor, Delivery, Recovery, and Postpartum (LDRP) private suites paired with an accredited Level-III NICU.",
    features: [
      "Private LDRP Birthing Suites with Luxury Amenities",
      "Accredited Level-III Giraffe Incubator NICU",
      "24/7 In-House Neonatal & Obstetric Emergency Coverage",
      "Continuous Wireless Maternal-Fetal Telemetry",
    ],
  },
  {
    id: "fac-6",
    title: "24/7 Automated Robotic Cold-Chain Central Pharmacy",
    category: "Pharmacy Logistics",
    capacity: "10,000+ Verified Drugs",
    badgeColor: "bg-teal-100 text-teal-800 border-teal-200",
    themeGradient: "from-teal-500 to-emerald-600",
    image: "/services/pharmacy.jpg",
    description: "High-speed Swisslog robotic dispensing system with strict 2-8°C biological cold-chain preservation and doorstep dispatch.",
    features: [
      "100% Barcode-Verified Dispensing Accuracy",
      "Continuous 2-8°C Digital Temperature Telemetry",
      "Automated Hospital Inpatient Refill Pneumatic Tubes",
      "Same-Day Regional Doorstep Medication Delivery",
    ],
  },
];

export const INITIAL_APPOINTMENTS = [
  {
    id: "apt-1",
    tokenNumber: "VC-8901",
    patientName: "Robert C. Davis",
    patientPhone: "+1 (555) 234-8901",
    patientEmail: "robert.davis@example.com",
    doctorName: "Dr. Arvind V. Nambiar",
    departmentName: "Heart & Vascular Sciences",
    appointmentDate: "Today",
    appointmentTime: "10:30 AM",
    status: "Confirmed",
    type: "In-Person Consultation",
    timestamp: new Date().toISOString(),
  },
  {
    id: "apt-2",
    tokenNumber: "VC-8902",
    patientName: "Sophia Hernandez",
    patientPhone: "+1 (555) 345-1290",
    patientEmail: "sophia.h@example.com",
    doctorName: "Dr. Sarah Jenkins",
    departmentName: "Orthopedics & Robotic Joints",
    appointmentDate: "Today",
    appointmentTime: "11:15 AM",
    status: "Confirmed",
    type: "Robotic Joint Review",
    timestamp: new Date().toISOString(),
  },
  {
    id: "apt-3",
    tokenNumber: "VC-8903",
    patientName: "Michael Chang",
    patientPhone: "+1 (555) 890-4412",
    patientEmail: "m.chang@example.com",
    doctorName: "Dr. Rajeshwar Rao",
    departmentName: "Neurosciences & Stroke Unit",
    appointmentDate: "Today",
    appointmentTime: "12:00 PM",
    status: "In-Consultation",
    type: "MRI Follow-up",
    timestamp: new Date().toISOString(),
  },
  {
    id: "apt-4",
    tokenNumber: "VC-8904",
    patientName: "Amanda Wright",
    patientPhone: "+1 (555) 762-9011",
    patientEmail: "amanda.w@example.com",
    doctorName: "Dr. Elena Rostova",
    departmentName: "Women, Maternity & Neonatology",
    appointmentDate: "Tomorrow",
    appointmentTime: "09:45 AM",
    status: "Confirmed",
    type: "4D Fetal Scan",
    timestamp: new Date().toISOString(),
  },
  {
    id: "apt-5",
    tokenNumber: "VC-8905",
    patientName: "David K. Miller",
    patientPhone: "+1 (555) 431-7788",
    patientEmail: "david.m@example.com",
    doctorName: "Dr. Margaret Thorne",
    departmentName: "Comprehensive Cancer Institute",
    appointmentDate: "Tomorrow",
    appointmentTime: "10:30 AM",
    status: "Confirmed",
    type: "Immunotherapy Protocol",
    timestamp: new Date().toISOString(),
  },
  {
    id: "apt-6",
    tokenNumber: "VC-8906",
    patientName: "Priya Sharma",
    patientPhone: "+1 (555) 902-3341",
    patientEmail: "priya.s@example.com",
    doctorName: "Dr. Arvind V. Nambiar",
    departmentName: "Heart & Vascular Sciences",
    appointmentDate: "Tomorrow",
    appointmentTime: "11:30 AM",
    status: "Confirmed",
    type: "Echo Diagnostic Review",
    timestamp: new Date().toISOString(),
  },
];

export const INITIAL_STATS = {
  totalAppointments: 14850,
  todayFootfall: 428,
  activeDoctors: 124,
  bedOccupancyRate: "88.4%",
  traumaReadiness: "100% Ready",
  hospital: INITIAL_HOSPITAL_INFO,
};
